baseURL      = "nutudragos.github.io/"
title        = "Dragos Nutu"
languageCode = "en-us"
theme        = "hello-friend-ng"
relativeURLs = true
# canonifyURLs = true
enableThemeToggle = false

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "I post some of my work here. Currently preparing for OSCP"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "My cyberblog"
  keywords = "homepage, blog, cyber, cyberblog, cybersecurity"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[params.logo]
    logoText = "whoami"

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #  
  # Addon: Startpage portrait 
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # Uncomment this if you want a portrait on your start page
  #
[params.portrait]
    path     = "/img/me.jpeg"
    alt      = "my portrait"
  #   maxWidth = "50px"

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #  
  # Addon: Commento
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # Commento is more than just a comments widget you can embed — 
  # it’s a return to the roots of the internet. 
  # An internet without the tracking and invasions of privacy. 
  # An internet that is simple and lightweight. 
  # An internet that is focused on interesting discussions, not ads. 
  # A better internet.
  # Uncomment this to enable Commento.
  #
  # [params.commento]
  #   url = ""




#[languages]
#  [languages.en]
#    title = "Hello Friend NG"
#    keywords = ""
#    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
#    readOtherPosts = "Read other posts"

#  [languages.en.params]
#    subtitle  = "A simple theme for Hugo"

#    [languages.en.params.logo]
#      logoText = "hello friend ng"
#      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    name       = "Writeups"
    url        = "/writeups"
  [[menu.main]]
    name       = "Resume"
    url        = "/resume"
  [[menu.main]]
    name       = "Projects"
    url        = "/projects"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
